<?php

declare(strict_types=1);

return [
    [
        'slug' => 'bulk-meta-update',
        'name' => 'Bulk Meta Update',
        'description' => 'Upload CSV files to update WordPress user meta in bulk with automatic logging.',
        'entry' => 'bulk-meta-update/index.php',
        'category' => 'Data Ops',
        'tags' => ['wordpress', 'csv', 'meta'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
        'requires_auth' => true,
    ],
    [
        'slug' => 'company-update',
        'name' => 'Company Update Worker',
        'description' => 'Headless worker scripts for company profile maintenance (launch via CLI).',
        'entry' => 'company_update/batch-company.php',
        'category' => 'Automation',
        'tags' => ['cli', 'company', 'maintenance'],
        'type' => 'cli',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
        'notes' => 'Run from shell: php company_update/batch-company.php',
    ],
    [
        'slug' => 'course-report',
        'name' => 'Course Completion Report',
        'description' => 'Convert identifiers into LearnDash completion reports by uploading a CSV.',
        'entry' => 'course_report/course-report.php',
        'category' => 'Reporting',
        'tags' => ['learndash', 'csv', 'reports'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'csv-column-mapper',
        'name' => 'CSV Column Mapper',
        'description' => 'Prepare and map inbound CSV data before importing into WordPress.',
        'entry' => 'csv-column-mapper/index.html',
        'category' => 'Data Prep',
        'tags' => ['csv', 'mapping'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'division-update',
        'name' => 'Division Update Worker',
        'description' => 'Command-line batch scripts for managing LearnDash divisions and groups.',
        'entry' => 'division_update/batch-groups.php',
        'category' => 'Automation',
        'tags' => ['cli', 'division', 'learndash'],
        'type' => 'cli',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
        'notes' => 'Run from shell: php division_update/batch-groups.php',
    ],
    [
        'slug' => 'port-pulse-builder',
        'name' => 'Port Pulse Builder',
        'description' => 'React + Tailwind app for composing Port Pulse newsletters with live preview.',
        'entry' => 'port-pulse-builder/index.html',
        'category' => 'Communications',
        'tags' => ['react', 'newsletter'],
        'type' => 'web',
        'status' => 'beta',
        'version' => 'v2.0.0',
    ],
    [
        'slug' => 'wp-bulk-column-updater',
        'name' => 'WP Bulk Column Updater',
        'description' => 'Launcher + worker for updating LearnDash enrollment columns in bulk.',
        'entry' => 'wp-bulk-column-updater/index.php',
        'category' => 'WordPress',
        'tags' => ['wordpress', 'learndash'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'wp-cli-scripts',
        'name' => 'WP CLI Scripts',
        'description' => 'Utility shell scripts (e.g., count logged-in users) that must run via CLI.',
        'entry' => 'wp-cli-scripts/count-logged-in-users.sh',
        'category' => 'Automation',
        'tags' => ['cli', 'wordpress'],
        'type' => 'cli',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
        'notes' => 'Run from shell: bash wp-cli-scripts/count-logged-in-users.sh',
    ],
    [
        'slug' => 'wp-ld-tools',
        'name' => 'LearnDash Tools',
        'description' => 'Web helpers for LearnDash finishers, reminder emails, and user lookups.',
        'entry' => 'wp-ld-tools/index.html',
        'category' => 'LearnDash',
        'tags' => ['learndash', 'support'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'wp-mailer',
        'name' => 'WP Mailer',
        'description' => 'Front-end launcher for background email campaigns with live logs.',
        'entry' => 'wp-mailer/index.html',
        'category' => 'Email',
        'tags' => ['mailer', 'cli'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
        'requires_auth' => true,
    ],
    [
        'slug' => 'wp-remove-course-3027',
        'name' => 'Remove Course 3027',
        'description' => 'Specialized UI for unenrolling users from Course 3027 safely.',
        'entry' => 'wp-remove-course-3027/index.php',
        'category' => 'LearnDash',
        'tags' => ['learndash', 'cleanup'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'wp-resigned-processor',
        'name' => 'Resigned Processor',
        'description' => 'Uploads CSV lists of resigned users and processes access removals.',
        'entry' => 'wp-resigned-processor/index.html',
        'category' => 'Lifecycle',
        'tags' => ['csv', 'automation'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'wp-user-exporter',
        'name' => 'WP User Exporter',
        'description' => 'Generate CSV exports of WordPress users with division filters.',
        'entry' => 'wp-user-exporter/index.html',
        'category' => 'Data Ops',
        'tags' => ['csv', 'exports'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
    [
        'slug' => 'wp-user-mod',
        'name' => 'User Modification Console',
        'description' => 'Token-gated interface to search and edit WordPress user data and meta.',
        'entry' => 'wp-user-mod/user_mod.php',
        'category' => 'Support',
        'tags' => ['wordpress', 'support'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
        'requires_auth' => true,
    ],
    [
        'slug' => 'wp-welcome-sender',
        'name' => 'Welcome Sender',
        'description' => 'CSV-driven welcome email launcher with logging and status pages.',
        'entry' => 'wp-welcome-sender/index.html',
        'category' => 'Lifecycle',
        'tags' => ['email', 'csv'],
        'type' => 'web',
        'status' => 'stable',
        'version' => 'v15.09.0002.0001',
    ],
];
